### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by alfredchiesa** [sbmsc/hacktoberfest#136]
Hey @sbmsc - I couldn't find your contact information anywhere, but I'm hoping to chat about the `midnight` account. We had GitHub release the old username after waiting a couple years for the old account to expire. Looks like you might have grabbed it in the moments between it being released and us renaming our org. My contact is alfred@midnight.sh - hoping we can figure this out.

**Comment by sbmsc** [comment]
closing this as it doesn't relate to the subject of the repo.
